from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('catalog/', views.catalog, name='catalog'),
    path('product/<slug:slug>/', views.product, name='product'),
    path('cart/', views.cart, name='cart'),
    path('cart/add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('cart/remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('cart/update/<int:product_id>/', views.cart_update, name='cart_update'),
    path('cart/clear/', views.cart_clear, name='cart_clear'),
    path('account/', views.account, name='account'),
    path('account/update/', views.profile_update, name='profile_update'),
    path('account/password/', views.password_change, name='password_change'),
    path('account/address/add/', views.address_save, name='address_add'),
    path('account/address/<int:pk>/edit/', views.address_save, name='address_edit'),
    path('account/address/<int:pk>/delete/', views.address_delete, name='address_delete'),
    path('account/address/<int:pk>/default/', views.address_set_default, name='address_set_default'),
    path('order/<int:pk>/repeat/', views.order_repeat, name='order_repeat'),
    path('checkout/', views.checkout, name='checkout'),
    path('order/success/', views.order_success, name='order_success'),
    path('quick-order/', views.quick_order, name='quick_order'),
    path('wishlist/toggle/<int:product_id>/', views.wishlist_toggle, name='wishlist_toggle'),

    path('auth/', views.auth, name='auth'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='shop/auth.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='index'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='shop/password_reset.html',
        email_template_name='shop/password_reset_email.html',
        subject_template_name='shop/password_reset_subject.txt',
        success_url='/password-reset/done/',
    ), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='shop/password_reset_done.html',
    ), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='shop/password_reset_confirm.html',
        success_url='/password-reset/complete/',
    ), name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='shop/password_reset_complete.html',
    ), name='password_reset_complete'),
    path('panel/', views.admin_panel, name='admin_panel'),
    path('panel/order/<int:pk>/', views.order_detail_json, name='order_detail_json'),
    path('panel/order/<int:pk>/status/', views.order_set_status, name='order_set_status'),
    path('panel/product/new/', views.product_save, name='product_create'),
    path('panel/product/<int:pk>/edit/', views.product_save, name='product_update'),
    path('panel/product/<int:pk>/delete/', views.product_delete, name='product_delete'),
    path('panel/product/<int:pk>/json/', views.product_detail_json, name='product_detail_json'),
    path('panel/orders/export/', views.orders_export_csv, name='orders_export_csv'),
    path('panel/product/<int:product_id>/packaging/add/', views.packaging_option_save, name='packaging_option_save'),
    path('panel/product/packaging/<int:pk>/delete/', views.packaging_option_delete, name='packaging_option_delete'),
    path('panel/product/<int:product_id>/image/add/', views.product_image_add, name='product_image_add'),
    path('panel/product/image/<int:pk>/delete/', views.product_image_delete, name='product_image_delete'),
    path('panel/category/new/', views.category_save, name='category_create'),
    path('panel/category/<int:pk>/edit/', views.category_save, name='category_update'),
    path('panel/category/<int:pk>/delete/', views.category_delete, name='category_delete'),
    path('panel/category/<int:pk>/json/', views.category_detail_json, name='category_detail_json'),
    path('panel/reports/', views.reports_data, name='reports_data'),
    path('panel/reports/export/', views.reports_export, name='reports_export'),
    path('panel/reports/sales/', views.reports_sales, name='reports_sales'),
    path('panel/reports/customers/', views.reports_customers, name='reports_customers'),
    path('panel/reports/stock/', views.reports_stock, name='reports_stock'),
    path('panel/inventory/<int:product_id>/update/', views.inventory_update, name='inventory_update'),
    path('panel/global-packaging/', views.global_packaging_list, name='global_packaging_list'),
    path('panel/global-packaging/add/', views.global_packaging_save, name='global_packaging_create'),
    path('panel/global-packaging/<int:pk>/edit/', views.global_packaging_save, name='global_packaging_update'),
    path('panel/global-packaging/<int:pk>/delete/', views.global_packaging_delete, name='global_packaging_delete'),
    path('panel/orders/poll/', views.orders_poll, name='orders_poll'),
    path('panel/banner/', views.banner_get, name='banner_get'),
    path('panel/banner/save/', views.banner_save, name='banner_save'),
]
