# Generated by Django 5.2.14 on 2026-05-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='extras',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Доп. параметры'),
        ),
    ]
