# Generated by Django 5.2.14 on 2026-05-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_packagingoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPackagingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Надбавка к цене')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Глобальный вид упаковки',
                'ordering': ['order', 'id'],
            },
        ),
    ]
